export const data = [
	{
		type: "Bungalow",
		img: require("../images/about1.jpg"),
		name: "Xclusive Lodge",
		price: "100k/month",
		location: "Ikeja, Lagos",
		agent: "Portablex",
	},
	{
		type: "Hotels",
		img: require("../images/about2.jpg"),
		name: "Xclusive Lodge",
		price: "100k/month",
		location: "Ikeja, Lagos",
		agent: "Portablex",
	},
	{
		type: "skyscraper",
		img: require("../images/type.png"),
		name: "Xclusive Lodge",
		price: "100k/month",
		location: "Ikeja, Lagos",
		agent: "Portablex",
	},
	{
		type: "Flats",
		img: require("../images/about2.jpg"),
		name: "Xclusive Lodge",
		price: "100k/month",
		location: "Ikeja, Lagos",
		agent: "Portablex",
	},
	{
		type: "skyscraper",
		img: require("../images/about1.jpg"),
		name: "Xclusive Lodge",
		price: "100k/month",
		location: "Ikeja, Lagos",
		agent: "Portablex",
	},
	{
		type: "Flats",
		img: require("../images/hero.png"),
		name: "Xclusive Lodge",
		price: "100k/month",
		location: "Ikeja, Lagos",
		agent: "Portablex",
	},
	{
		type: "Duplex",
		img: require("../images/type.png"),
		name: "Xclusive Lodge",
		price: "100k/month",
		location: "Ikeja, Lagos",
		agent: "Portablex",
	},
	{
		type: "Hotels",
		img: require("../images/about2.jpg"),
		name: "Xclusive Lodge",
		price: "100k/month",
		location: "Ikeja, Lagos",
		agent: "Portablex",
	},
	{
		type: "Bungalow",
		img: require("../images/about2.jpg"),
		name: "Xclusive Lodge",
		price: "100k/month",
		location: "Ikeja, Lagos",
		agent: "Portablex",
	},
	{
		type: "Duplex",
		img: require("../images/type.png"),
		name: "Xclusive Lodge",
		price: "100k/month",
		location: "Ikeja, Lagos",
		agent: "Portablex",
	},
	{
		type: "Self contain",
		img: require("../images/about2.jpg"),
		name: "Xclusive Lodge",
		price: "100k/month",
		location: "Ikeja, Lagos",
		agent: "Portablex",
	},
	{
		type: "Self contain",
		img: require("../images/hero.png"),
		name: "Xclusive Lodge",
		price: "100k/month",
		location: "Ikeja, Lagos",
		agent: "Portablex",
	},
];
