export const agentTransaction = [
	{
		status: true,
		description: "tolulope@gmail.com",
		amount: "390,000.00",
		type: "Card",
		date: "Today at 5:00 PM",
	},
	{
		status: true,
		description: "tolulope@gmail.com",
		amount: "390,000.00",
		type: "Card",
		date: "Today at 5:00 PM",
	},
	{
		status: false,
		description: "tolulope@gmail.com",
		amount: "390,000.00",
		type: "Card",
		date: "Today at 5:00 PM",
	},
	{
		status: true,
		description: "tolulope@gmail.com",
		amount: "390,000.00",
		type: "Card",
		date: "Today at 5:00 PM",
	},
	{
		status: false,
		description: "tolulope@gmail.com",
		amount: "390,000.00",
		type: "Card",
		date: "Today at 5:00 PM",
	},
	{
		status: true,
		description: "tolulope@gmail.com",
		amount: "390,000.00",
		type: "Card",
		date: "Today at 5:00 PM",
	},
	{
		status: false,
		description: "tolulope@gmail.com",
		amount: "390,000.00",
		type: "Card",
		date: "Today at 5:00 PM",
	},
	{
		status: true,
		description: "tolulope@gmail.com",
		amount: "390,000.00",
		type: "Card",
		date: "Today at 5:00 PM",
	},
	{
		status: true,
		description: "tolulope@gmail.com",
		amount: "390,000.00",
		type: "Card",
		date: "Today at 5:00 PM",
	},
	{
		status: true,
		description: "tolulope@gmail.com",
		amount: "390,000.00",
		type: "Card",
		date: "Today at 5:00 PM",
	},
	
];
